### ISSUE TITLE
Use TOML syntax for `tox` configuration

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#180]
Possible since Tox v4.21.0, see https://tox.wiki/en/4.21.0/config.html#pyproject-toml-native. Example:

```toml
[tool.tox]
requires = ["tox>=4.19"]
env_list = ["3.13", "3.12", "type"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
commands = [["pytest"]]

[tool.tox.env.type]
description = "run type check on code base"
deps = ["mypy==1.11.2", "types-cachetools>=5.5.0.20240820", "types-chardet>=5.0.4.6"]
commands = [["mypy", "src{/}tox"], ["mypy", "tests"]]
```

```[tasklist]
### Tasks
- [ ] https://github.com/tamasfe/taplo/issues/624
- [ ] https://github.com/ComPWA/policy/issues/409
- [x] Define `tox.ini` to `pyproject.toml` converter
- [x] Set minimal `tox` version to v4.21.0
- [x] Investigate problems with `base` key
```

```[tasklist]
### Related PRs
- [ ] https://github.com/ComPWA/ampform/pull/447
- [ ] https://github.com/ComPWA/ampform-dpd/pull/149
- [ ] https://github.com/ComPWA/benchmarks/pull/27
- [ ] https://github.com/ComPWA/compwa.github.io/pull/302
- [ ] https://github.com/ComPWA/demo/pull/42
- [ ] https://github.com/ComPWA/gluex-nstar/pull/109
- [ ] https://github.com/ComPWA/gluex-nstar-analysis/pull/78
- [ ] https://github.com/ComPWA/K-matrix-research/pull/102
- [ ] https://github.com/ComPWA/Nstar-docs/pull/29
- [ ] https://github.com/ComPWA/polarimetry/pull/372
- [ ] https://github.com/ComPWA/PWA-JPsi2pbarSigmaKS/pull/113
- [ ] https://github.com/ComPWA/PWA-pages/pull/230
- [ ] https://github.com/ComPWA/report/pull/27
- [ ] https://github.com/ComPWA/qrules/pull/315
- [ ] https://github.com/ComPWA/sphinx-hep-pdgref/pull/44
- [ ] https://github.com/ComPWA/strong2020-salamanca/pull/45
- [ ] https://github.com/ComPWA/tensorwaves/pull/538
- [ ] https://github.com/RUB-EP1/pawian-tools/pull/57
```

**Comment by redeboer** [comment]
Since [`tox` v4.21.0](https://github.com/tox-dev/tox/releases/tag/4.21.0), it should be possible to merge the job definitions under `tox.ini` into `pyproject.toml` 🎉 That removes yet another configuration file (see https://github.com/ComPWA/policy/issues/180).

**Comment by redeboer** [comment]
The `commands` key in the native `pyproject.toml` configuration uses nested arrays. Since we set Taplo to sort arrays, we would have to use [Rules](https://taplo.tamasfe.dev/configuration/file.html#rules) to prevent the `commands` key from being sorted. In `.taplo.toml`:

```toml
[[rule]]
include = ["**/pyproject.toml"]
keys = ["tool.tox"]

[rule.formatting]
reorder_arrays = false
```

Rules are a new feature in Taplo v0.9 though, which is not yet available in VS Code, see https://github.com/tamasfe/taplo/issues/624. So long as that is not the case, we get situations where a configuration like

```toml
[tool.tox.env.example]
commands = [
    ["pytest", "--no-header"],
]
```

is autoformatted as

```toml
[tool.tox.env.example]
commands = [
    ["--no-header", "pytest"],
]
```
