### ISSUE TITLE
Switch to pre-commit mirror for `black`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#208]
### Suggestion

[This page](https://black.readthedocs.io/en/stable/integrations/source_version_control.html) claims that [`black`s official mirror repository](https://github.com/psf/black-pre-commit-mirror) is twice as fast as listing the [`black` repository](https://github.com/psf/black) itself as a pre-commit hook.

### Proposed solution

Replace the `https://github.com/psf/black` with `https://github.com/psf/black-pre-commit-mirror`

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/repo-maintenance/pull/209
- [ ] https://github.com/ComPWA/repo-maintenance/pull/210
- [ ] https://github.com/ComPWA/qrules/pull/234
- [ ] https://github.com/ComPWA/ampform/pull/363
- [ ] https://github.com/ComPWA/ampform-dpd/pull/83
- [ ] https://github.com/ComPWA/tensorwaves/pull/504
- [ ] https://github.com/ComPWA/compwa-org/pull/215
- [ ] https://github.com/ComPWA/PWA-pages/pull/199
- [ ] https://github.com/ComPWA/strong2020-salamanca/pull/31
- [ ] https://github.com/ComPWA/PWA-JPsi2pbarSigmaKS/pull/71
```
