### ISSUE TITLE
Do not run PR linting if PR is not open

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#303]
Simply add

```yaml
if: github.event.pull_request.state == 'open'
```
to each job under `pr-linting.yaml`.

Optionally, we can outsource the linting to [`ComPWA/actions/.github/workflows/pr-linting.yml`](https://github.com/ComPWA/actions/blob/e383765c7ce2c9ce5bc09d2b6935a7c2c139c9ac/.github/workflows/pr-linting.yml) if it is gets a workflow call.
```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/policy/pull/304
- [ ] https://github.com/ComPWA/actions/pull/64
- [ ] https://github.com/ComPWA/actions/pull/65
- [ ] https://github.com/ComPWA/policy/pull/307
```
