### ISSUE TITLE
Speed up creation of developer environment

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#333]
Conda in combination with pip is quite slow. Elsewhere, where possible, we now use `uv pip`, but Conda's [`environment.yml`](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) does not support `uv pip install` statements, see https://github.com/conda/conda/issues/13833.

Some alternatives are listed in https://github.com/ComPWA/policy/issues/256#issuecomment-1987310158

```[tasklist]
### Related Pull Requests
- [ ] https://github.com/ComPWA/policy/issues/404
- [ ] https://github.com/ComPWA/.github/pull/26
- [ ] https://github.com/ComPWA/.github-private/pull/5
- [ ] https://github.com/ComPWA/actions/pull/103
- [ ] https://github.com/ComPWA/ampform/pull/439
- [ ] https://github.com/ComPWA/ampform-dpd/pull/142
- [ ] https://github.com/ComPWA/benchmarks/pull/24
- [ ] https://github.com/ComPWA/compwa.github.io/pull/301
- [ ] https://github.com/ComPWA/demo/pull/39
- [ ] https://github.com/ComPWA/gluex-amplitude/pull/34
- [ ] https://github.com/ComPWA/gluex-nstar/pull/107
- [ ] https://github.com/ComPWA/jax-mini-benchmark/pull/11
- [ ] https://github.com/ComPWA/K-matrix-research/pull/97
- [ ] https://github.com/ComPWA/Nstar-docs/pull/26
- [ ] https://github.com/ComPWA/polarimetry/pull/364
- [ ] https://github.com/ComPWA/PWA-JPsi2pbarSigmaKS/pull/80
- [ ] https://github.com/ComPWA/PWA-pages/pull/228
- [ ] https://github.com/ComPWA/qrules/pull/289
- [ ] https://github.com/ComPWA/report/pull/23
- [ ] https://github.com/ComPWA/sphinx-api-relink/pull/31
- [ ] https://github.com/ComPWA/sphinx-hep-pdgref/pull/42
- [ ] https://github.com/ComPWA/sphinx-pybtex-etal-style/pull/10
- [ ] https://github.com/ComPWA/strong2020-salamanca/pull/41
- [ ] https://github.com/ComPWA/tensorwaves/pull/533
```

> [!TIP]
> All ComPWA repositories are listed [here](https://github.com/orgs/ComPWA/repositories?q=mirror%3Afalse+fork%3Afalse+archived%3Afalse+sort%3Aname-asc).

**Comment by redeboer** [comment]
Some uodated thoughts on this in https://github.com/ComPWA/kmatrix/pull/1#discussion_r1727060430
