### ISSUE TITLE
Refactorings for `check-dev-files` hook

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#334]
```[tasklist]
### Tasks
- [x] Define abstract interface for `ModifiablePrecommit` and `ModifiablePyproject`
- [ ] Update ComPWA `check-dev-files` module descriptions
- [ ] Provide directory argument to `check-dev-files`
- [ ] Write tests for `check-dev-files`
```

**Comment by redeboer** [comment]
Closed by #630 through https://github.com/ComPWA/policy/pull/652
