### ISSUE TITLE
Use `ubuntu-24.04` image in GitHub workflows

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#397]
The workflows on [ComPWA/policy](https://github.com/ComPWA/policy) and [ComPWA/actions](https://github.com/ComPWA/actions) (and [possibly other repos](https://github.com/search?q=org%3AComPWA+ubuntu-22.04&type=code)) can now run with the `ubuntu-24.04` image. See [this blog post](https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available).

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/actions/pull/86
- [ ] https://github.com/ComPWA/policy/pull/414
- [ ] https://github.com/ComPWA/actions/issues/85
```
