### ISSUE TITLE
Switch to built-in VS Code test coverage visualization

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#400]
The Python extension in VS Code now has [built-in test coverage support](https://code.visualstudio.com/docs/python/testing#_run-tests-with-coverage), see [this blog post](https://code.visualstudio.com/updates/v1_94#_python) and [vscode-python v2024.16.0](https://github.com/microsoft/vscode-python/releases/tag/v2024.16.0). This would remove the need for the [Coverage Gutters extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) and the need to run `tox -e cov` before seeing coverage.

### Tasks
- [x] Update to [`coverage>=7.7.0`](https://pypi.org/project/coverage/7.7.0)
- [x] Remove `--no-cov` from `python.testing.pytestArgs`
- [x] Remove Coverage Gutters extension
- [x] Make sure that only `src/` is included in the coverage computation

**Comment by redeboer** [comment]
Closed by https://github.com/ComPWA/policy/pull/516 🎉
