### ISSUE TITLE
Remove Codacy badges

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#463]
We no longer use Codacy as a service (replaces by local linters). See here which repos have a Codacy badge:
https://github.com/search?q=org%3AComPWA+codacy.com+-is%3Aarchived&type=code

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/ampform/pull/447
- [ ] https://github.com/ComPWA/qrules/pull/315
- [ ] https://github.com/ComPWA/sphinx-hep-pdgref/pull/44
- [ ] https://github.com/ComPWA/tensorwaves/pull/538
```
