### ISSUE TITLE
Fix Codecov reports

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#464]
The link between Codecov and some repositories appears to have broken. See e.g. https://app.codecov.io/gh/ComPWA/qrules/commits.

```[tasklist]
### Tasks
- [x] Upgrade to [`codecov/codecov-action`](https://github.com/codecov/codecov-action) v5 https://github.com/ComPWA/actions/pull/118
- [ ] https://github.com/ComPWA/policy/pull/487
- [ ] https://github.com/ComPWA/actions/pull/123
```

```[tasklist]
### Implementation PRs
- [ ] https://github.com/ComPWA/PWA-pages/pull/230
- [ ] https://github.com/ComPWA/ampform/pull/447
- [ ] https://github.com/ComPWA/ampform-dpd/pull/149
- [ ] https://github.com/ComPWA/qrules/pull/315
- [ ] https://github.com/ComPWA/sphinx-hep-pdgref/pull/44
- [ ] https://github.com/ComPWA/tensorwaves/pull/538
- [ ] https://github.com/RUB-EP1/pawian-tools/pull/57
```
