### ISSUE TITLE
Switch to `sphinx.ext.linkcode` extension

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#60]
GitHub nowadays offers [much better code navigation](https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github) for source code of Python packages, also for specific commits. In addition, you immediately have features like Git blame in the browser. It therefore seems that [`sphinx.ext.linkcode`](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) than [`viewcode`](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html), which we use now. Many packages like numpy and pandas switched to `linkcode` as well.

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/sphinx-api-relink/pull/8
- [ ] https://github.com/ComPWA/repo-maintenance/pull/242
- [ ] QRules
- [ ] https://github.com/ComPWA/ampform/pull/371
- [ ] AmpForm-DPD
- [ ] TensorWaves
- [ ] Polarimetry
```
