### ISSUE TITLE
Run notebooks in MyST-NB with caching

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#67]
In most ComPWA repositories, `conf.py` sets [`nb_execution_mode`](https://myst-nb.readthedocs.io/en/v0.15.0/computation/execute.html#notebook-execution-modes) to `"force"` if `EXECUTE_NB` is defined as an environment variable. This should be changed to `"cache"`, so that we make full use of MyST-NB's caching functionality.

It may also be worth defining some `tox` jobs for inspecting the [Juypyter cache](https://jupyter-cache.rtfd.io) files.

```[tasklist]
### Tasks
- [ ] https://github.com/ComPWA/qrules/pull/178
- [ ] https://github.com/ComPWA/ampform/pull/286
- [ ] https://github.com/ComPWA/tensorwaves/pull/433
- [ ] https://github.com/ComPWA/compwa-org/pull/144
- [ ] https://github.com/ComPWA/PWA-pages/pull/162
```
