### ISSUE TITLE
Migrate to `sphinx-design`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#74]
[`sphinx-panels`](https://sphinx-panels.rtfd.io) is no longer maintained. See [here](https://sphinx-design.readthedocs.io/en/latest/get_started.html#migrating-from-sphinx-panels) how to migrate to [`sphinx-design`](https://sphinx-design.rtfd.io).

### To-do

- [x] https://github.com/ComPWA/qrules/pull/189
- [x] https://github.com/ComPWA/ampform/pull/299
- [x] https://github.com/ComPWA/tensorwaves/pull/450
- [x] https://github.com/ComPWA/compwa-org/pull/158
- [x] https://github.com/ComPWA/PWA-pages/pull/170
