### ISSUE TITLE
Switch to Read the Docs `build.commands`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#76]
Read the Docs builds for a [config that customizes the build](https://docs.readthedocs.io/en/stable/build-customization.html) (for dependency pinning) **fail since today** (compare [this one](https://readthedocs.org/projects/compwa-org/builds/17115849/) with [this one](https://readthedocs.org/projects/compwa-org/builds/17117139/), because one now needs to [explicitly define `build.commands`](https://docs.readthedocs.io/en/stable/build-customization.html#override-the-build-process). This may also help to implement caching for [`jupyter-cache`](https://jupyter-cache.readthedocs.io).

```[tasklist]
### To-do
- [x] https://github.com/ComPWA/ampform
- [x] https://github.com/ComPWA/tensorwaves
- [x] https://github.com/ComPWA/compwa-org
- [x] https://github.com/ComPWA/PWA-pages
```

```[tasklist]
### Related PRs and commits
- [ ] https://github.com/ComPWA/qrules/pull/172
- [ ] https://github.com/ComPWA/ampform/pull/276
- [ ] https://github.com/ComPWA/tensorwaves/pull/429
- [x] ComPWA/compwa.github.io@9e3367d
```
